// Code generated by MockGen. DO NOT EDIT.
// Source: avatar.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/DimKa163/goph-profile/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// ActivateOnlyThis mocks base method.
func (m *MockAvatarRepository) ActivateOnlyThis(arg0 context.Context, arg1 entity.Email, arg2 entity.AvatarID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateOnlyThis", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateOnlyThis indicates an expected call of ActivateOnlyThis.
func (mr *MockAvatarRepositoryMockRecorder) ActivateOnlyThis(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateOnlyThis", reflect.TypeOf((*MockAvatarRepository)(nil).ActivateOnlyThis), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockAvatarRepository) Delete(ctx context.Context, id entity.AvatarID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarRepository)(nil).Delete), ctx, id)
}

// DeleteImages mocks base method.
func (m *MockAvatarRepository) DeleteImages(ctx context.Context, id entity.AvatarID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImages", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImages indicates an expected call of DeleteImages.
func (mr *MockAvatarRepositoryMockRecorder) DeleteImages(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImages", reflect.TypeOf((*MockAvatarRepository)(nil).DeleteImages), ctx, id)
}

// Find mocks base method.
func (m *MockAvatarRepository) Find(ctx context.Context, id entity.AvatarID) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAvatarRepositoryMockRecorder) Find(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAvatarRepository)(nil).Find), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockAvatarRepository) FindByUserID(arg0 context.Context, arg1 entity.Email) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockAvatarRepositoryMockRecorder) FindByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).FindByUserID), arg0, arg1)
}

// FindImage mocks base method.
func (m *MockAvatarRepository) FindImage(ctx context.Context, avatarID entity.AvatarID) ([]*entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindImage", ctx, avatarID)
	ret0, _ := ret[0].([]*entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindImage indicates an expected call of FindImage.
func (mr *MockAvatarRepositoryMockRecorder) FindImage(ctx, avatarID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindImage", reflect.TypeOf((*MockAvatarRepository)(nil).FindImage), ctx, avatarID)
}

// Insert mocks base method.
func (m *MockAvatarRepository) Insert(ctx context.Context, id entity.AvatarID, name string, userID entity.Email, width, height int, size int64, mimeType string, rows ...*entity.Image) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, id, name, userID, width, height, size, mimeType}
	for _, a := range rows {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockAvatarRepositoryMockRecorder) Insert(ctx, id, name, userID, width, height, size, mimeType interface{}, rows ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, id, name, userID, width, height, size, mimeType}, rows...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAvatarRepository)(nil).Insert), varargs...)
}

// InsertImage mocks base method.
func (m *MockAvatarRepository) InsertImage(ctx context.Context, e *entity.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertImage", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertImage indicates an expected call of InsertImage.
func (mr *MockAvatarRepositoryMockRecorder) InsertImage(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertImage", reflect.TypeOf((*MockAvatarRepository)(nil).InsertImage), ctx, e)
}

// ListByUserID mocks base method.
func (m *MockAvatarRepository) ListByUserID(arg0 context.Context, arg1 entity.Email) ([]*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAvatarRepositoryMockRecorder) ListByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).ListByUserID), arg0, arg1)
}
