// Code generated by MockGen. DO NOT EDIT.
// Source: codec.go

// Package mocks is a generated GoMock package.
package mocks

import (
	image "image"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockImageCodec is a mock of ImageCodec interface.
type MockImageCodec struct {
	ctrl     *gomock.Controller
	recorder *MockImageCodecMockRecorder
}

// MockImageCodecMockRecorder is the mock recorder for MockImageCodec.
type MockImageCodecMockRecorder struct {
	mock *MockImageCodec
}

// NewMockImageCodec creates a new mock instance.
func NewMockImageCodec(ctrl *gomock.Controller) *MockImageCodec {
	mock := &MockImageCodec{ctrl: ctrl}
	mock.recorder = &MockImageCodecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageCodec) EXPECT() *MockImageCodecMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockImageCodec) Decode(r io.Reader) (image.Image, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", r)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Decode indicates an expected call of Decode.
func (mr *MockImageCodecMockRecorder) Decode(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockImageCodec)(nil).Decode), r)
}

// DecodeConfig mocks base method.
func (m *MockImageCodec) DecodeConfig(r io.ReadSeeker) (image.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeConfig", r)
	ret0, _ := ret[0].(image.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeConfig indicates an expected call of DecodeConfig.
func (mr *MockImageCodecMockRecorder) DecodeConfig(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeConfig", reflect.TypeOf((*MockImageCodec)(nil).DecodeConfig), r)
}

// Encode mocks base method.
func (m *MockImageCodec) Encode(src image.Image, format string, quality int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", src, format, quality)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockImageCodecMockRecorder) Encode(src, format, quality interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockImageCodec)(nil).Encode), src, format, quality)
}

// Thumbnail mocks base method.
func (m *MockImageCodec) Thumbnail(src image.Image, h, w int) image.Image {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Thumbnail", src, h, w)
	ret0, _ := ret[0].(image.Image)
	return ret0
}

// Thumbnail indicates an expected call of Thumbnail.
func (mr *MockImageCodecMockRecorder) Thumbnail(src, h, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Thumbnail", reflect.TypeOf((*MockImageCodec)(nil).Thumbnail), src, h, w)
}
