apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: goph-profile-netpol
  namespace: {{ .Chart.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Chart.Name }}

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Chart.Name }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.postgres.namespace }}

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.minio.namespace }}

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.kafka.namespace }}

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.monitoring.namespace }}

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
