apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Values.accountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Values.accountName }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Values.accountName }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Chart.Name }}
    name: {{ .Values.accountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.accountName }}
