// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetAvatarParamsSize.
const (
	GetAvatarParamsSizeN100x100 GetAvatarParamsSize = "100x100"
	GetAvatarParamsSizeN300x300 GetAvatarParamsSize = "300x300"
	GetAvatarParamsSizeOriginal GetAvatarParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetAvatarParamsSize enum.
func (e GetAvatarParamsSize) Valid() bool {
	switch e {
	case GetAvatarParamsSizeN100x100:
		return true
	case GetAvatarParamsSizeN300x300:
		return true
	case GetAvatarParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetAvatarParamsFormat.
const (
	GetAvatarParamsFormatJpeg GetAvatarParamsFormat = "jpeg"
	GetAvatarParamsFormatPng  GetAvatarParamsFormat = "png"
	GetAvatarParamsFormatWebp GetAvatarParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetAvatarParamsFormat enum.
func (e GetAvatarParamsFormat) Valid() bool {
	switch e {
	case GetAvatarParamsFormatJpeg:
		return true
	case GetAvatarParamsFormatPng:
		return true
	case GetAvatarParamsFormatWebp:
		return true
	default:
		return false
	}
}

// Defines values for GetCurrentUserAvatarParamsSize.
const (
	GetCurrentUserAvatarParamsSizeN100x100 GetCurrentUserAvatarParamsSize = "100x100"
	GetCurrentUserAvatarParamsSizeN300x300 GetCurrentUserAvatarParamsSize = "300x300"
	GetCurrentUserAvatarParamsSizeOriginal GetCurrentUserAvatarParamsSize = "original"
)

// Valid indicates whether the value is a known member of the GetCurrentUserAvatarParamsSize enum.
func (e GetCurrentUserAvatarParamsSize) Valid() bool {
	switch e {
	case GetCurrentUserAvatarParamsSizeN100x100:
		return true
	case GetCurrentUserAvatarParamsSizeN300x300:
		return true
	case GetCurrentUserAvatarParamsSizeOriginal:
		return true
	default:
		return false
	}
}

// Defines values for GetCurrentUserAvatarParamsFormat.
const (
	GetCurrentUserAvatarParamsFormatJpeg GetCurrentUserAvatarParamsFormat = "jpeg"
	GetCurrentUserAvatarParamsFormatPng  GetCurrentUserAvatarParamsFormat = "png"
	GetCurrentUserAvatarParamsFormatWebp GetCurrentUserAvatarParamsFormat = "webp"
)

// Valid indicates whether the value is a known member of the GetCurrentUserAvatarParamsFormat enum.
func (e GetCurrentUserAvatarParamsFormat) Valid() bool {
	switch e {
	case GetCurrentUserAvatarParamsFormatJpeg:
		return true
	case GetCurrentUserAvatarParamsFormatPng:
		return true
	case GetCurrentUserAvatarParamsFormatWebp:
		return true
	default:
		return false
	}
}

// AvatarMetadata defines model for AvatarMetadata.
type AvatarMetadata struct {
	CreatedAt  time.Time           `json:"created_at"`
	Dimension  Dimension           `json:"dimension"`
	FileName   string              `json:"file_name"`
	Id         string              `json:"id"`
	Inactive   bool                `json:"inactive"`
	MimeType   string              `json:"mime_type"`
	Size       int64               `json:"size"`
	Thumbnails []Thumbnail         `json:"thumbnails"`
	UpdatedAt  time.Time           `json:"updated_at"`
	UserId     openapi_types.Email `json:"userId"`
}

// Dimension defines model for Dimension.
type Dimension struct {
	Height int `json:"height"`
	Width  int `json:"width"`
}

// ServiceError defines model for ServiceError.
type ServiceError struct {
	// Code Example: invalid_avatar_id
	Code *string `json:"code,omitempty"`

	// Message Example: invalid avatar id
	Message *string `json:"message,omitempty"`
}

// Thumbnail defines model for Thumbnail.
type Thumbnail struct {
	Size string `json:"size"`
	Url  string `json:"url"`
}

// UploadAvatarResponse defines model for UploadAvatarResponse.
type UploadAvatarResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`

	// Status Example: processing
	Status string              `json:"status"`
	Url    string              `json:"url"`
	UserId openapi_types.Email `json:"userId"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ServiceError

// FileTooLarge defines model for FileTooLarge.
type FileTooLarge = ServiceError

// Forbidden defines model for Forbidden.
type Forbidden = ServiceError

// InternalError defines model for InternalError.
type InternalError = ServiceError

// NotFound defines model for NotFound.
type NotFound = ServiceError

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	Image openapi_types.File `json:"image"`
}

// UploadAvatarParams defines parameters for UploadAvatar.
type UploadAvatarParams struct {
	XUserID *string `json:"X-User-ID,omitempty"`
}

// DeleteAvatarParams defines parameters for DeleteAvatar.
type DeleteAvatarParams struct {
	XUserID string `json:"X-User-ID"`
}

// GetAvatarParams defines parameters for GetAvatar.
type GetAvatarParams struct {
	Size        *GetAvatarParamsSize   `form:"size,omitempty" json:"size,omitempty"`
	Format      *GetAvatarParamsFormat `form:"format,omitempty" json:"format,omitempty"`
	XUserID     string                 `json:"X-User-ID"`
	IfNoneMatch *string                `json:"If-None-Match,omitempty"`
}

// GetAvatarParamsSize defines parameters for GetAvatar.
type GetAvatarParamsSize string

// GetAvatarParamsFormat defines parameters for GetAvatar.
type GetAvatarParamsFormat string

// GetAvatarMetadataParams defines parameters for GetAvatarMetadata.
type GetAvatarMetadataParams struct {
	XUserID string `json:"X-User-ID"`
}

// GetCurrentUserAvatarParams defines parameters for GetCurrentUserAvatar.
type GetCurrentUserAvatarParams struct {
	Size        *GetCurrentUserAvatarParamsSize   `form:"size,omitempty" json:"size,omitempty"`
	Format      *GetCurrentUserAvatarParamsFormat `form:"format,omitempty" json:"format,omitempty"`
	IfNoneMatch *string                           `json:"If-None-Match,omitempty"`
}

// GetCurrentUserAvatarParamsSize defines parameters for GetCurrentUserAvatar.
type GetCurrentUserAvatarParamsSize string

// GetCurrentUserAvatarParamsFormat defines parameters for GetCurrentUserAvatar.
type GetCurrentUserAvatarParamsFormat string

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// UploadAvatar Upload avatar
	// (POST /avatars)
	UploadAvatar(ctx *echo.Context, params UploadAvatarParams) error
	// DeleteAvatar Delete avatar
	// (DELETE /avatars/{avatar_id})
	DeleteAvatar(ctx *echo.Context, avatarId string, params DeleteAvatarParams) error
	// GetAvatar Get avatar image
	// (GET /avatars/{avatar_id})
	GetAvatar(ctx *echo.Context, avatarId string, params GetAvatarParams) error
	// GetAvatarMetadata Get avatar metadata
	// (GET /avatars/{avatar_id}/metadata)
	GetAvatarMetadata(ctx *echo.Context, avatarId string, params GetAvatarMetadataParams) error
	// DeleteUserAvatar Delete current user avatar
	// (DELETE /users/{user_id}/avatar)
	DeleteUserAvatar(ctx *echo.Context, userId string) error
	// GetCurrentUserAvatar Get current user avatar image
	// (GET /users/{user_id}/avatar)
	GetCurrentUserAvatar(ctx *echo.Context, userId string, params GetCurrentUserAvatarParams) error
	// GetAllUserAvatars Get all user avatars
	// (GET /users/{user_id}/avatars)
	GetAllUserAvatars(ctx *echo.Context, userId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// UploadAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) UploadAvatar(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadAvatarParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = &XUserID
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadAvatar(ctx, params)
	return err
}

// DeleteAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAvatar(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId string

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteAvatarParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAvatar(ctx, avatarId, params)
	return err
}

// GetAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatar(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId string

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvatarParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}
	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for If-None-Match, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter If-None-Match: %s", err))
		}

		params.IfNoneMatch = &IfNoneMatch
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatar(ctx, avatarId, params)
	return err
}

// GetAvatarMetadata converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatarMetadata(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "avatar_id" -------------
	var avatarId string

	err = runtime.BindStyledParameterWithOptions("simple", "avatar_id", ctx.Param("avatar_id"), &avatarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter avatar_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvatarMetadataParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-User-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-User-ID: %s", err))
		}

		params.XUserID = XUserID
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-User-ID is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatarMetadata(ctx, avatarId, params)
	return err
}

// DeleteUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUserAvatar(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteUserAvatar(ctx, userId)
	return err
}

// GetCurrentUserAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUserAvatar(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCurrentUserAvatarParams
	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", ctx.QueryParams(), &params.Size, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter size: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Optional header parameter "If-None-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-None-Match")]; found {
		var IfNoneMatch string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for If-None-Match, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-None-Match", valueList[0], &IfNoneMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter If-None-Match: %s", err))
		}

		params.IfNoneMatch = &IfNoneMatch
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUserAvatar(ctx, userId, params)
	return err
}

// GetAllUserAvatars converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllUserAvatars(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllUserAvatars(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/avatars", wrapper.UploadAvatar, options.OperationMiddlewares["uploadAvatar"]...)
	router.DELETE(options.BaseURL+"/avatars/:avatar_id", wrapper.DeleteAvatar, options.OperationMiddlewares["deleteAvatar"]...)
	router.GET(options.BaseURL+"/avatars/:avatar_id", wrapper.GetAvatar, options.OperationMiddlewares["getAvatar"]...)
	router.GET(options.BaseURL+"/avatars/:avatar_id/metadata", wrapper.GetAvatarMetadata, options.OperationMiddlewares["getAvatarMetadata"]...)
	router.DELETE(options.BaseURL+"/users/:user_id/avatar", wrapper.DeleteUserAvatar, options.OperationMiddlewares["deleteUserAvatar"]...)
	router.GET(options.BaseURL+"/users/:user_id/avatar", wrapper.GetCurrentUserAvatar, options.OperationMiddlewares["getCurrentUserAvatar"]...)
	router.GET(options.BaseURL+"/users/:user_id/avatars", wrapper.GetAllUserAvatars, options.OperationMiddlewares["getAllUserAvatars"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FhNb9tGE/4rxL7vkTKpyu1Bt8RODAONEaQOUCAwjBU5ktbgfmR3qNg1+N+L2aVEUqRl2VCVJuhJ1HK+",
	"duaZeUZ6ZJmWRitQ6Nj0kVlwRisH/stbnn+CryU4pG+ZVgjKP3JjCpFxFFold04rOnPZEiSnp/9bmLMp",
	"+1/SmE7CW5f8AXYlMnhnrbasqqqY5eAyKwzZYlNyGdnaZxWz96KAa61/53YBR4uBnEaodVR4txSGtjOR",
	"56COF8PGYxWzS4VgFS+C9LFCWHuNIEjE7Erje12q/GghXGmM5t4jvau1yOibFUduPwDynKN3Y6w2YFEE",
	"5GYWOEJ+y32Ac20lPbGcI4xQSGAxwwcDbMocWqEWdLtcSFBOhPh3RX2+EaxiNhcF3CouPTx7NkU+fKx4",
	"hmLV1plpXQD3JqWQcBuOB3Sd+As6lxIKfzttLiQUwgJ8vXBZypniovA5EQjSPXe367WK1w8WubX8gb6X",
	"Jn9xVksH9jLvyIMk+z3ZKmbU+cJCzqZfKHUb7Xaa2/mps9GuXefWrUzHbUx0rnKziUTP7iDzc+e8jYUu",
	"tJYgFktslaaV8G8ix+XQq6271TbWCkMRdFqjj2+dexDAPZemCK5WvBD5Lfedceuz1yuGBOf4YlgzCprR",
	"kGY1EGCDlF50a4j2wWCLgfOt5JBQXdihxHw2heZ5GACfarY6zAB4olkdcixdN2fG6gycI4l432serBfq",
	"gLYRbYuBfFV+2sw1Oe3O1pDByFhNvRW5gDcKRaC/44U2y+hj/frNx0sWsxXY0BRsfJKepHQnbUBxI9iU",
	"TU7SkwmLmeG49OlKAqL8s9FhiaAaeaagPHRq6TUtl4BAKl8emSBHS+A50MswY9mfo88O7OjynMUtktlO",
	"303IHzh8q/OHLb6SZYHCcIsJlWG0ZpDGWhdKQtYtsynaTChuH56vmlccrkkjh7YEf9BavH5Jxwfj2MF+",
	"GeDaIBfxLAODkFNtT9P0KeubcJPWkkgq48nzKp2trorZr/v46S5Bfh8opaQ6NLGvgYR8QRCqMe7YDYmv",
	"4Zg8bmZkFdqiAIQ+OM/9+U5wEtQbaLZHb7e+u6Aa7wH0/a3d9JB02m/9Kx2tofXKKqf7VLm9wp6GOHZr",
	"bPbLQ2AilG8XJmK2gIGhdAH4gxX9KWuX89GVVjD6wDFbsn0sfC3BD7baQL1dNXqgSklJ1FYshOLEXOM0",
	"vR+nKYvZJE3vJ2namnjP2a8n6pCHOwPErcYz7DeYmSGzfbSnW3PTz+DEG+tMzH1medClCF6p6sN+oW5v",
	"Ltc8Hcgkrmvsb3vGsyWMzrRCq4uun35E7675YrcMSU2GxwVGUudiLl5PC0dv/wvAzUZbp25vVkhk64fl",
	"7hmx+Qn64xJEerBVYyslT4N5k9+fl35a+JMNRoYhSJu9Sx7pw8Ov5qxndxOq/wuoqrb/r9wnvtN2kJXW",
	"gsKIUtNfFSi/uxeFs6B/hEL8x/E/McfXMOoS1j9IxweZbgO906PadQc9PeXcTo4tiqa13BGH3Ms4ca9/",
	"VrfJcfvv1YFf5E1i3fcsNC+KdpHdUH1JCexqXRj/DxhLuBHJasyqm+rvAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
