{
 "title": "Processing avatar",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total uploads by userID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status, user_id) (\r\n  avatars_uploads_total\r\n)",
     "legendFormat": "{{status}}({{user_id}})"
    }
   ]
  },
  {
   "title": "Storatage usage(top 100)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n    100,\r\n    sum by (user_id) (\r\n    avatars_storage_bytes\r\n    )\r\n)",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Upload avatar duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, status) (rate(avatars_upload_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing avatar duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, kind, status) (rate(avatars_processing_duration_seconds_bucket{kind=\"uploaded\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}