name: goph-profile
run-name: testing goph-profile
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go
      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Vet
        run: go vet ./...


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go

      - name: Run tests
        run: go test -race -cover ./...


  build-server:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go

      - name: Build server-app
        run: |
          mkdir -p build
          go build -ldflags "-X main.Name=goph-server -X 'main.BuildDate=$(date +'%Y/%m/%d %H:%M:%S')' -X 'main.Commit=$(git rev-parse --short HEAD)'" -o build/server-app ./cmd/server

      - name: Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: server-app
          path: build/server-app
          if-no-files-found: error
          retention-days: 3


  build-outbox:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go=

      - name: Build outbox-app
        run: |
          mkdir -p build
          go build -ldflags "-X main.Name=goph-outbox  -X 'main.BuildDate=$(date +'%Y/%m/%d %H:%M:%S')' -X 'main.Commit=$(git rev-parse --short HEAD)'" -o build/outbox-app ./cmd/outbox

      - name: Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: outbox-app
          path: build/outbox-app
          if-no-files-found: error
          retention-days: 3

  build-inbox:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go=

      - name: Build inbox-app
        run: |
          mkdir -p build
          go build -ldflags "-X main.Name=goph-inbox  -X 'main.BuildDate=$(date +'%Y/%m/%d %H:%M:%S')' -X 'main.Commit=$(git rev-parse --short HEAD)'" -o build/inbox-app ./cmd/inbox

      - name: Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: inbox-app
          path: build/inbox-app
          if-no-files-found: error
          retention-days: 3