// Code generated by MockGen. DO NOT EDIT.
// Source: avatar.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	image "image"
	io "io"
	reflect "reflect"

	entity "github.com/DimKa163/goph-profile/internal/entity"
	kafka "github.com/DimKa163/goph-profile/internal/infra/kafka"
	guid "github.com/beevik/guid"
	gomock "github.com/golang/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAvatarRepository) Find(ctx context.Context, id guid.Guid) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAvatarRepositoryMockRecorder) Find(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAvatarRepository)(nil).Find), ctx, id)
}

// Insert mocks base method.
func (m *MockAvatarRepository) Insert(ctx context.Context, name, mimeType string, size int64, width, height int, userID guid.Guid) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, name, mimeType, size, width, height, userID)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockAvatarRepositoryMockRecorder) Insert(ctx, name, mimeType, size, width, height, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAvatarRepository)(nil).Insert), ctx, name, mimeType, size, width, height, userID)
}

// Update mocks base method.
func (m *MockAvatarRepository) Update(ctx context.Context, e *entity.Avatar) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, e)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAvatarRepositoryMockRecorder) Update(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAvatarRepository)(nil).Update), ctx, e)
}

// MockS3 is a mock of S3 interface.
type MockS3 struct {
	ctrl     *gomock.Controller
	recorder *MockS3MockRecorder
}

// MockS3MockRecorder is the mock recorder for MockS3.
type MockS3MockRecorder struct {
	mock *MockS3
}

// NewMockS3 creates a new mock instance.
func NewMockS3(ctrl *gomock.Controller) *MockS3 {
	mock := &MockS3{ctrl: ctrl}
	mock.recorder = &MockS3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3) EXPECT() *MockS3MockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockS3) Download(ctx context.Context, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockS3MockRecorder) Download(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockS3)(nil).Download), ctx, key)
}

// Upload mocks base method.
func (m *MockS3) Upload(ctx context.Context, key string, reader io.ReadSeeker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockS3MockRecorder) Upload(ctx, key, reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockS3)(nil).Upload), ctx, key, reader)
}

// MockProducer is a mock of Producer interface.
type MockProducer struct {
	ctrl     *gomock.Controller
	recorder *MockProducerMockRecorder
}

// MockProducerMockRecorder is the mock recorder for MockProducer.
type MockProducerMockRecorder struct {
	mock *MockProducer
}

// NewMockProducer creates a new mock instance.
func NewMockProducer(ctrl *gomock.Controller) *MockProducer {
	mock := &MockProducer{ctrl: ctrl}
	mock.recorder = &MockProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducer) EXPECT() *MockProducerMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockProducer) Write(ctx context.Context, key, value []byte, headers ...kafka.Header) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key, value}
	for _, a := range headers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Write", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockProducerMockRecorder) Write(ctx, key, value interface{}, headers ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key, value}, headers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockProducer)(nil).Write), varargs...)
}

// MockImageCodec is a mock of ImageCodec interface.
type MockImageCodec struct {
	ctrl     *gomock.Controller
	recorder *MockImageCodecMockRecorder
}

// MockImageCodecMockRecorder is the mock recorder for MockImageCodec.
type MockImageCodecMockRecorder struct {
	mock *MockImageCodec
}

// NewMockImageCodec creates a new mock instance.
func NewMockImageCodec(ctrl *gomock.Controller) *MockImageCodec {
	mock := &MockImageCodec{ctrl: ctrl}
	mock.recorder = &MockImageCodecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageCodec) EXPECT() *MockImageCodecMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockImageCodec) Decode(r io.Reader) (image.Image, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", r)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Decode indicates an expected call of Decode.
func (mr *MockImageCodecMockRecorder) Decode(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockImageCodec)(nil).Decode), r)
}

// DecodeConfig mocks base method.
func (m *MockImageCodec) DecodeConfig(r io.ReadSeeker) (image.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeConfig", r)
	ret0, _ := ret[0].(image.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeConfig indicates an expected call of DecodeConfig.
func (mr *MockImageCodecMockRecorder) DecodeConfig(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeConfig", reflect.TypeOf((*MockImageCodec)(nil).DecodeConfig), r)
}

// Encode mocks base method.
func (m *MockImageCodec) Encode(src image.Image, format string, quality int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", src, format, quality)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockImageCodecMockRecorder) Encode(src, format, quality interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockImageCodec)(nil).Encode), src, format, quality)
}

// Thumbnail mocks base method.
func (m *MockImageCodec) Thumbnail(src image.Image, h, w int) image.Image {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Thumbnail", src, h, w)
	ret0, _ := ret[0].(image.Image)
	return ret0
}

// Thumbnail indicates an expected call of Thumbnail.
func (mr *MockImageCodecMockRecorder) Thumbnail(src, h, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Thumbnail", reflect.TypeOf((*MockImageCodec)(nil).Thumbnail), src, h, w)
}
