// Code generated by MockGen. DO NOT EDIT.
// Source: upload.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	image "image"
	io "io"
	reflect "reflect"

	entity "github.com/DimKa163/goph-profile/internal/entity"
	guid "github.com/beevik/guid"
	gomock "github.com/golang/mock/gomock"
)

// MockS3Uploader is a mock of S3Uploader interface.
type MockS3Uploader struct {
	ctrl     *gomock.Controller
	recorder *MockS3UploaderMockRecorder
}

// MockS3UploaderMockRecorder is the mock recorder for MockS3Uploader.
type MockS3UploaderMockRecorder struct {
	mock *MockS3Uploader
}

// NewMockS3Uploader creates a new mock instance.
func NewMockS3Uploader(ctrl *gomock.Controller) *MockS3Uploader {
	mock := &MockS3Uploader{ctrl: ctrl}
	mock.recorder = &MockS3UploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Uploader) EXPECT() *MockS3UploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockS3Uploader) Upload(ctx context.Context, key string, reader io.ReadSeeker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockS3UploaderMockRecorder) Upload(ctx, key, reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockS3Uploader)(nil).Upload), ctx, key, reader)
}

// MockAvatarInsertUpdaterRepository is a mock of AvatarInsertUpdaterRepository interface.
type MockAvatarInsertUpdaterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarInsertUpdaterRepositoryMockRecorder
}

// MockAvatarInsertUpdaterRepositoryMockRecorder is the mock recorder for MockAvatarInsertUpdaterRepository.
type MockAvatarInsertUpdaterRepositoryMockRecorder struct {
	mock *MockAvatarInsertUpdaterRepository
}

// NewMockAvatarInsertUpdaterRepository creates a new mock instance.
func NewMockAvatarInsertUpdaterRepository(ctrl *gomock.Controller) *MockAvatarInsertUpdaterRepository {
	mock := &MockAvatarInsertUpdaterRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarInsertUpdaterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarInsertUpdaterRepository) EXPECT() *MockAvatarInsertUpdaterRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockAvatarInsertUpdaterRepository) Insert(ctx context.Context, name, mimeType string, size int64, width, height int, userID guid.Guid) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, name, mimeType, size, width, height, userID)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockAvatarInsertUpdaterRepositoryMockRecorder) Insert(ctx, name, mimeType, size, width, height, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAvatarInsertUpdaterRepository)(nil).Insert), ctx, name, mimeType, size, width, height, userID)
}

// Update mocks base method.
func (m *MockAvatarInsertUpdaterRepository) Update(ctx context.Context, e *entity.Avatar) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, e)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAvatarInsertUpdaterRepositoryMockRecorder) Update(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAvatarInsertUpdaterRepository)(nil).Update), ctx, e)
}

// MockDecoder is a mock of Decoder interface.
type MockDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockDecoderMockRecorder
}

// MockDecoderMockRecorder is the mock recorder for MockDecoder.
type MockDecoderMockRecorder struct {
	mock *MockDecoder
}

// NewMockDecoder creates a new mock instance.
func NewMockDecoder(ctrl *gomock.Controller) *MockDecoder {
	mock := &MockDecoder{ctrl: ctrl}
	mock.recorder = &MockDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecoder) EXPECT() *MockDecoderMockRecorder {
	return m.recorder
}

// DecodeConfig mocks base method.
func (m *MockDecoder) DecodeConfig(r io.ReadSeeker) (image.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeConfig", r)
	ret0, _ := ret[0].(image.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeConfig indicates an expected call of DecodeConfig.
func (mr *MockDecoderMockRecorder) DecodeConfig(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeConfig", reflect.TypeOf((*MockDecoder)(nil).DecodeConfig), r)
}
