name: goph-profile
run-name: testing goph-profile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go
      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Vet
        run: go vet ./...


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go

      - name: Run tests
        run: go test -race -cover ./...


  build-server:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            server_binary: goph-server-linux
            outbox_binary: goph-outbox-linux
            inbox_binary: goph-inbox-linux
          - os: windows-latest
            server_binary: goph-server.exe
            outbox_binary: goph-outbox.exe
            inbox_binary: goph-inbox.exe
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go

      - name: Build server-app
        run: |
          mkdir -p build
          go build -ldflags "-X main.Name=goph-server -X main.Version=${{ github.ref_name }} \
            -X 'main.BuildDate=$(date -u +'%Y-%m-%d_%H:%M:%S')'\
          -X 'main.Commit=${{ github.sha }}" -o ${{matrix.server_binary}} ./cmd/server

      - name: Server artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.server_binary }}
          path: ${{ matrix.server_binary }}
          retention-days: 30

      - name: Build outbox-app
        run: |
          mkdir -p build
          go build -ldflags "-X main.Name=goph-outbox -X main.Version=${{ github.ref_name }} \
            -X 'main.BuildDate=$(date -u +'%Y-%m-%d_%H:%M:%S')'\
          -X 'main.Commit=${{ github.sha }}" -o ${{matrix.outbox_binary}} ./cmd/outbox

      - name: Outbox artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.outbox_binary }}
          path: ${{ matrix.outbox_binary }}
          retention-days: 30

      - name: Build inbox-app
        run: |
          mkdir -p build
          go build -ldflags "-X main.Name=goph-inbox -X main.Version=${{ github.ref_name }} \
            -X 'main.BuildDate=$(date -u +'%Y-%m-%d_%H:%M:%S')'\
          -X 'main.Commit=${{ github.sha }}" -o ${{matrix.inbox_binary}} ./cmd/inbox

      - name: Inbox artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.inbox_binary }}
          path: ${{ matrix.inbox_binary }}
          retention-days: 30